import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, Legend, PieChart, Pie, Cell } from "recharts";
import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { useLang } from "@/context/LangContext";
import { formatMoney, localizeAgingBuckets, localizeMonthLabels } from "@/lib/utils";

const STATUS_COLORS = { draft: "var(--ink-muted)", sent: "var(--accent)", overdue: "var(--danger)", paid: "var(--success)" };
const tooltipStyle = { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, fontSize: 12, color: "var(--ink)" };

export default function ReportsCharts({ monthly, statusData, aging, agingHasData, topClients, maxClient }) {
  const { t } = useLang();
  const localizedAging = localizeAgingBuckets(aging, t);
  const localizedMonthly = localizeMonthLabels(monthly);
  return (
    <>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        <Card padding="lg" className="h-full lg:col-span-2"><CardHeader><div><CardTitle>{t("reports.revVsExp")}</CardTitle><CardDescription>{t("reports.revVsExpDesc")}</CardDescription></div></CardHeader><ResponsiveContainer width="100%" height={280}><BarChart data={localizedMonthly} margin={{ top: 8, right: 4, bottom: 0, left: -8 }}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "var(--ink-muted)", fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "var(--ink-muted)", fontSize: 12 }} tickFormatter={(v) => (v >= 1000 ? `${v / 1000}k` : v)} /><Tooltip cursor={{ fill: "var(--surface-2)" }} contentStyle={tooltipStyle} formatter={(v, n) => [formatMoney(v), n]} /><Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} /><Bar name={t("reports.csv.revenue")} dataKey="revenue" fill="var(--accent)" radius={[5, 5, 0, 0]} maxBarSize={28} /><Bar name={t("reports.csv.expenses")} dataKey="expenses" fill="var(--warning)" radius={[5, 5, 0, 0]} maxBarSize={28} /></BarChart></ResponsiveContainer></Card>
        <Card padding="lg"><CardHeader><div><CardTitle>{t("reports.invoiceStatus")}</CardTitle><CardDescription>{t("reports.byAmount")}</CardDescription></div></CardHeader>{statusData.length ? <><ResponsiveContainer width="100%" height={180}><PieChart><Pie data={statusData} dataKey="value" innerRadius={50} outerRadius={72} paddingAngle={2} stroke="none">{statusData.map((s) => <Cell key={s.key} fill={STATUS_COLORS[s.key]} />)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(v, n) => [formatMoney(v), t("status." + String(n || "draft").toLowerCase())]} /></PieChart></ResponsiveContainer><div className="space-y-2 mt-2">{statusData.map((s) => <div key={s.key} className="flex items-center gap-2 text-sm"><span className="h-2.5 w-2.5 rounded-full shrink-0" style={{ background: STATUS_COLORS[s.key] }} /><span className="text-[var(--ink-muted)] flex-1">{t("status." + (s.key || "draft"))}</span><span className="tabular font-medium text-[var(--ink)]">{formatMoney(s.value)}</span></div>)}</div></> : <div className="h-[220px] flex items-center justify-center text-sm text-[var(--ink-muted)]">{t("dash.noInvoices")}</div>}</Card>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><Card padding="lg"><CardHeader><div><CardTitle>{t("reports.aging")}</CardTitle><CardDescription>{t("reports.agingDesc")}</CardDescription></div></CardHeader>{agingHasData ? <ResponsiveContainer width="100%" height={240}><BarChart data={localizedAging} margin={{ top: 8, right: 4, bottom: 0, left: -8 }}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} /><XAxis dataKey="bucket" axisLine={false} tickLine={false} tick={{ fill: "var(--ink-muted)", fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "var(--ink-muted)", fontSize: 12 }} tickFormatter={(v) => (v >= 1000 ? `${v / 1000}k` : v)} /><Tooltip cursor={{ fill: "var(--surface-2)" }} contentStyle={tooltipStyle} formatter={(v) => [formatMoney(v), t("reports.csv.amount")]} /><Bar dataKey="value" radius={[5, 5, 0, 0]} maxBarSize={48}>{localizedAging.map((a, i) => <Cell key={i} fill={i === 0 ? "var(--accent)" : i >= 3 ? "var(--danger)" : "var(--warning)"} />)}</Bar></BarChart></ResponsiveContainer> : <div className="h-[240px] flex items-center justify-center text-sm text-[var(--ink-muted)]">{t("reports.allCaughtUp")}</div>}</Card><Card padding="lg"><CardHeader><div><CardTitle>{t("reports.topClients")}</CardTitle><CardDescription>{t("reports.byTotalBilled")}</CardDescription></div></CardHeader>{topClients.length ? <div className="space-y-4 pt-1">{topClients.map((client) => <div key={client.id}><div className="flex items-center justify-between text-sm mb-1.5"><span className="font-medium text-[var(--ink)] truncate">{client.name}</span><span className="tabular font-semibold text-[var(--ink)] shrink-0 ml-3">{formatMoney(client.billed)}</span></div><div className="h-2 rounded-full bg-[var(--surface-2)] overflow-hidden"><div className="h-full rounded-full" style={{ width: `${Math.max(4, (client.billed / maxClient) * 100)}%`, background: "linear-gradient(90deg,var(--accent),var(--accent-hero-2))" }} /></div></div>)}</div> : <div className="h-[240px] flex items-center justify-center text-sm text-[var(--ink-muted)]">{t("reports.noClientBilling")}</div>}</Card></div>
    </>
  );
}
